### ISSUE TITLE
bert-base-uncased path error

### ISSUE THREAD

**Issue by guahunyo** [portu-sim/sd-webui-bmab#13]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/18573180/d7ce7439-398d-4011-84d0-0d45cb70d34c)
final text_encoder_type: bert-base-uncased
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001FE656889D0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 8bfd0896-77bb-4ffc-aa3d-be1812f8f177)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001FE656889D0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 8bfd0896-77bb-4ffc-aa3d-be1812f8f177)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001FE656889D0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 8bfd0896-77bb-4ffc-aa3d-be1812f8f177)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json

I think I'm missing https://huggingface.co/bert-base-uncased/blob/main/tokenizer.json

so i downloaded it,  but  i don't know  where to put it

**Comment by portu-sim** [comment]
Oops.. For program compatibility, several modules were removed and there is currently a problem with the imaging function. Please wait. I'll try to find a solution.

**Comment by guahunyo** [comment]
> 哎呀..为了程序兼容性，删除了几个模块，目前成像功能有问题。请稍等。我会尝试找到解决方案。

**Comment by guahunyo** [comment]
> Oops.. For program compatibility, several modules were removed and there is currently a problem with the imaging function. Please wait. I'll try to find a solution.

ok
