### ISSUE TITLE
bmab10月30号之后的版本一直都有bug影响controlnet预处理图区域

### ISSUE THREAD

**Issue by XiaoCC** [portu-sim/sd-webui-bmab#15]
bmab10月30号之后的版本一直都有bug，会导致局部重绘 仅蒙版重绘的时候  controlnet的预处理图区域不对，比如我重绘一张照片的人脸，没更新bmab10月30号之前的版本时候，预处理图也是仅蒙版区域的，一旦更新了bmab10月30号之后的版本，预处理图就变成全图了，导致局部重绘仅蒙版功能异常

**Comment by portu-sim** [comment]
I think it's a preview problem. The latest version has fixed the issue where the preview does not appear correctly. Are you using the latest version?

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/16f4be7c-b756-44db-966b-eb728e620464)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/adbe2c59-76b3-40be-8e32-1ec80b84c6fb)
![image](https:github.com/portu-sim/sd-webui-bmab/assets/7299222/0830d45f-3d31-4af3-94ec-012113f74250)
这是10月30日版本的插件  局部重绘仅蒙版 openpose预处理图也是局部的

**Comment by XiaoCC** [comment]
这是11月23的版本
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/d2532970-8b51-4906-8fe6-2921f01c2e46)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/f9c5f404-7f09-4f22-b01c-fc0df7570de9)

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/fad1a25a-fe4e-4b91-a5f2-5e6a371cb10f)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/6d783253-8def-4e1d-bc5a-72e94b1fb4c9)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/4f85cfef-0fd6-437b-9f1c-f0f6ea5730ac)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/3cc4f69a-3551-4afd-bbf0-9d4e63605c95)

**Comment by portu-sim** [comment]
I can't read Chinese. Can you write it in English?

**Comment by portu-sim** [comment]
I think this is a controlnet bug. Check if it works the same with BMAB turned off. If BMAB is turned off, it does not interfere with ControlNet operation under any circumstances.

**Comment by XiaoCC** [comment]
a50ee323d9f7add30f10ba424ca4ff14c4a3b287 I have updated to the latest version of the plugin and still have the size issue of the controlNet preprocessing diagram

**Comment by portu-sim** [comment]
What you are reporting is not an error in BMAB, but an error in ControlNet.

**Comment by XiaoCC** [comment]
But after I close the bmab plugin, the preprocessing diagram of controlnet is normal, I smudge the area, and only redraw the mask area 512*512 
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/49a80a26-1c45-40ce-a15a-1311f2593a3b)

**Comment by XiaoCC** [comment]
启用10月30号之后的插件，controlnet的预处理图变成全身图 ![image](https:github.com/portu-sim/sd-webui-bmab/assets/7299222/3a14f11f-3c9b-4931-b2c2-d69d9b661996) Causing a partial redraw of a mask-only area of the face will redraw a full-body portrait into it

**Comment by XiaoCC** [comment]
Equivalent to redrawing a full body portrait of the face, resulting in abnormal visuals

**Comment by portu-sim** [comment]
When I checked, the controlnet was operating incorrectly even when BMAB was turned off. I'll check again tonight. thanks for letting me know.

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/0f6dfd7a-bddc-493b-bb2a-db4bac4de43e)
I didn't check the bmab plugin, I just installed the version after October 30th, and I got a controlNet preprocessing exception.
After uninstalling or downgrading the plugin to the October 30th version, the ControlNet pre-processing image will be normal.

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/b20edec5-149a-4df9-9c98-0ca3741b4233)
fc5159fe4020a1c3f6c69079adee1d9d53ba392c  
I updated the latest version of the plugin yesterday and there is still an issue with the exception of the pre-processing graph,

I think it may be due to the plugin that the preprocessed image does not support only the masked area. Even if I choose only the masked area, the preprocessed image still provides the full image, not just the openpose. All other ControlNet preprocessed images provide the full image (not just the masked area)

**Comment by portu-sim** [comment]
<img width="339" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/0eeb2984-e22b-40d0-96c2-c5a94c24466e">
<img width="474" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/5e795fa1-f950-4b95-b6dd-3d9ecca7ccb0">
<img width="935" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/d90c99eb-ad8e-449d-bda2-835dee1bf0fc">
<img width="967" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/30f98a87-a093-464e-a9f8-01e528ad7799">

It's working well with yesterday's updated version. Are you sure that the Inpaint Area is set to Only masked?

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/d1f2168b-7082-4cb8-84e7-5afb0e34e086)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/64f9365c-376a-4fe2-b2f6-e86e7cb8d65b)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/be4916a8-e436-4698-877a-411ef19f8db7)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/17ec5bad-7a01-4fea-ad1c-6601ea3648cc)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/7181bf37-0232-450a-88b4-f853270bf8ff)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/51060239-7f62-4be7-a401-00641416dcb6)

**Comment by XiaoCC** [comment]
The resolution of the preprocessed image is also 512 * 512, but the content of the preprocessed image is to compress the full body image into a 512 * 512 canvas, not just take the part of the face

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/5965d643-9687-44b4-ad2a-207212bec514)
Plugins before October 30th, or preprocessed images generated after uninstalling the plugin, only generate a portion of the facial area proportionally

**Comment by portu-sim** [comment]
<img width="1897" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/619398e2-1e9b-4a33-b948-d80b82aa8487">

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/2dca165e-7234-44b3-84ff-0d11a5fdcd43)
Found the issue. There is a conflict between the version after October 30th and the Adetailer plugin. As long as both Adetailer and BMAB versions after October 30th are installed, a ControlNet pre-processing exception will appear. Adetailer can only coexist with BMAB versions before October 30th

**Comment by XiaoCC** [comment]
Is it because the controllNet script calls between plugins are not coordinated properly

**Comment by XiaoCC** [comment]
There's also the issue that Grounding doesn't seem to support cuda12.1

**Comment by portu-sim** [comment]
In my case the problem doesn't seem to appear because I'm not using ADetailer.
Since BMAB's Face Detailer is used, it would be a good idea to contact the ADetailer developer for this issue. (BMAB alone does not seem to cause the problem.)

Due to compatibility issues, GroudingDINO has been adjusted to operate with CPU.
The version that uses CUDA is a bit slow due to the problem of not being able to support MacOS, but it can be used as a CPU version.

**Comment by XiaoCC** [comment]
Perhaps there was an issue with my translation description. What I meant was that using Adetailer in combination with (bmab version dated October 30th) is normal, while using ControlNet with (bmab version greater than October 30th) is abnormal. Is it possible that BMab added some features after October 30th that caused a conflict with Adetailer. Do we need the author of Adetailer to fix this conflict?

**Comment by XiaoCC** [comment]
Or is it possible that versions of BMAB after October 30th have included the functionality of Adetailer and no longer require the Adetailer plugin?

**Comment by portu-sim** [comment]
It is open source and a single developer cannot test every plugin. I will look into the issue with ADetailer, but that doesn't mean I will necessarily fix it.

Try changing the ADetailer directory name from extensions/adetailer to zadetailer so that it loads behind BMAB. There is a possibility that it will be resolved.

**Comment by XiaoCC** [comment]
![image](https:github.com/portu-sim/sd-webui-bmab/assets/7299222/c98a5884-32ec-477f-9eab-ddcca85057eb)
This method does not work

**Comment by XiaoCC** [comment]
I tested each version and found that (1c117f2) was the last version that was compatible with other plugins

**Comment by portu-sim** [comment]
<img width="1664" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/b5ccaef1-7656-4e09-afc6-eac80a44ce72">

Did you restart sd-webui after changing the directory? There is no problem in operating with adetailer.

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/ddf5373b-35e0-4d99-b052-133ab216f605)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/4602dcb5-48e9-4a64-a558-88482b9e88c2)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/58c2ff7d-d265-4d28-87a7-9d4ac95127ef)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/4e8c3494-2d22-4f96-9450-220a34758119)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/a745821d-7bb4-49fe-aa76-24665106d5f1)

**Comment by XiaoCC** [comment]
To eliminate interference, I only enabled 3 plugins

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/eb246eff-2e3f-46a9-ab38-56daceabcc52)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/bd5c920e-7cbf-4818-9eef-7103697914a3)

**Comment by portu-sim** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/141602933/e752c56f-79f7-4b5d-be82-8af7a955d960)

**Comment by portu-sim** [comment]
I can't rollback to 10.30 version. The code is changed by other function. 
in other way...change name 'sd-webui-bmab' to 'a1sd-webui-bmab' and restart webui.

**Comment by XiaoCC** [comment]
(https:github.com/portu-sim/sd-webui-bmab/commit/1c117f20724fa3a456ec723fe2a6af76d1b8ba1f) was the last release on 11.7

**Comment by portu-sim** [comment]
I CANT USE THAT CODE. I CANT ROLLBACK TO 11.7. It changed for future work and new features.

**Comment by XiaoCC** [comment]
Okay then I'll use the 11.7 version first, hopefully a later version will solve it，thinks

**Comment by XiaoCC** [comment]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/34c96c7d-e510-47e4-9eb6-ee02bf0d16e7)
![image](https://github.com/portu-sim/sd-webui-bmab/assets/7299222/013b3076-d409-4b8c-be01-78d515a53ade)
It's normal after changing the directory name, it's amazing

**Comment by XiaoCC** [comment]
Problem solved, thank you very much😄
