### ISSUE TITLE
Please, SDNEXT backcompatibility.....

### ISSUE THREAD

**Issue by RGX650** [portu-sim/sd-webui-bmab#16]
I am not a developper, and i struggle to make it on my own really...
https://github.com/RGX650/sd-webui-bmab.git

I would be SO GRATEFULL  !!!

**Comment by portu-sim** [comment]
Does SDNEXT means this project? https://github.com/vladmandic/automatic

**Comment by RGX650** [comment]
Yes!

**Comment by Sunsphire** [comment]
I would love to see this working in SD.Next / Vladmandic repo!

**Comment by RGX650** [comment]
> I would love to see this working in SD.Next / Vladmandic repo!

i think i am almost done, maybe tonight or tomorrow...

**Comment by RGX650** [comment]
@Sunsphire you can git clone my repo, i have not tested it properlly yet, but you can use it now. Please dont hesitate to give me some feedback.   (as i said previously I am not a developper, but i spent A LOT of time on it. @portu-sim  I would really appreciate some review and inspection on my fork, please please please....

**Comment by portu-sim** [comment]
@RGX650 I'll check it..

**Comment by portu-sim** [comment]
@RGX650 Can you check out dev branch, fix the code and pull request your code?

**Comment by RGX650** [comment]
i added you as collaborator.

Also:
https://github.com/vladmandic/automatic/issues/2584

**Comment by vladmandic** [comment]
thanks for the work! see https://github.com/vladmandic/automatic/issues/2584#issuecomment-1863608958 for a bit more detailed response.

**Comment by RGX650** [comment]
MY CURRENT (self aware) PROBLEMATICS: (i might have more, fell free to enlight me!)

- regarding RNG.py : what would be the difference between using SDNEXT's "devices.backend"
  instead of the added shared.opts.randn_source ?

- slider value  synch between my BMAB's added shared.opts and SDNEXT's quick settings sliders ?


https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/sd_bmab/sd_override/txt2img.py

- SDNEXT StableDiffusionProcessingTxt2Img hasn't post init, so i used def init (self, **kwargs) and super init (**kwargs) instead.
  Also Field is not used in SDNEXT version 
  i am struggle regarding how BMAB StableDiffusionProcessingTxt2ImgOv class should inherits shape, seeds, subseeds, etc
  regarding its def sample(...) and its self.rng = rng.ImageRNG(...)

- SDNEXT hypertile seams implemented differently than in A1111, i just added hypertile_set(self) as i a barbarian in BMAB
  StableDiffusionProcessingTxt2ImgOv def sample


https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/sd_bmab/sd_override/samper.py

- HELP regarding: SDNEXT KDiffusionSampler modules.sd_samplers_kdiffusion compatibility

**Comment by RGX650** [comment]
However - besides torch size errors, in some case -  i would say it is "running"
(SDNEXT version update of the 20/12/23)

**Comment by portu-sim** [comment]
CLOSE THIS ISSUE.
