### ISSUE TITLE
기능 On 시 Title 강조하는 기능 추가

### ISSUE THREAD

**Issue by ThisisLandu** [portu-sim/sd-webui-bmab#17]
![image](https://github.com/portu-sim/sd-webui-bmab/assets/36629328/8f8163cb-d318-4ecd-b0e2-e77cb558453b)

컨트롤넷에서 여러 컨트롤넷 유닛 놓고
어떤 컨트롤넷유닛을 enable 로 체크하면 노란 타이틀로 바뀌면서 어떤기능이 켜져있는지 쉽게 확인할수 있습니다
BMAB에 좋은기능이 넘모 많아서 크고끄고할게많은데 이거 추가해서  한눈에 쉽게 체크했으면 좋겠읍니다

**Comment by portu-sim** [comment]
네 저도 원하는 기능이긴 한데....제가 잘 모르는 분야라서,
ControlNet 보고 한번 따라 해보기는 하겠습니다.

**Comment by portu-sim** [comment]
제가 할 수 없는 영역인 것 같아서 이 요청은 drop 하겠습니다.
