### ISSUE TITLE
When launching the web UI, I encounter an error message related to this plugin.

### ISSUE THREAD

**Issue by wibur0620** [portu-sim/sd-webui-bmab#2]
venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.019616499999756343
Launching Web UI with arguments: --xformers --no-half-vae --medvram-sdxl
[-] ADetailer initialized. version: 23.9.1, num models: 14
*** Error loading script: sd_webui_bmab.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-bmab\scripts\sd_webui_bmab.py", line 1, in <module>
        from sd_bmab.bmab import BmabExtScript
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-bmab\sd_bmab\bmab.py", line 13, in <module>
        from sd_bmab import dinosam, process, detailing, parameters, util, controlnet, constants
    ImportError: cannot import name 'dinosam' from 'sd_bmab' (D:\AI\stable-diffusion-webui\extensions\sd-webui-bmab\sd_bmab\__init__.py)

---
2023-09-09 18:07:26,503 - ControlNet - INFO - ControlNet v1.1.408
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-09 18:07:26,603 - ControlNet - INFO - ControlNet v1.1.408
sd-webui-prompt-all-in-one background API service started successfully.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
dirname:  D:\AI\stable-diffusion-webui\localizations
localizations:  {'zh-Hans (Stable) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable) [vladmandic].json', 'zh-Hans (Stable)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing) [vladmandic].json', 'zh-Hans (Testing)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
Loading weights [01e01ebb1d] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\SDXLRonghua_v20.safetensors
D:\AI\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
Running on local URL:  http://127.0.0.1:7860
Creating model from config: D:\AI\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 28.5s (prepare environment: 12.1s, import torch: 3.8s, import gradio: 1.1s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 6.5s, create ui: 1.2s, gradio launch: 0.6s, app_started_callback: 1.3s).
Applying attention optimization: xformers... done.
Model loaded in 14.1s (load weights from disk: 1.6s, create model: 1.6s, apply weights to model: 6.4s, apply half(): 0.2s, calculate empty prompt: 4.0s).

**Comment by wibur0620** [comment]
Reinstall, the problem disappears, and it can be used normally

--------------
venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.0057483999989926815
Launching Web UI with arguments: --xformers --no-half-vae --medvram-sdxl
[-] ADetailer initialized. version: 23.9.1, num models: 14
2023-09-09 18:48:57,368 - ControlNet - INFO - ControlNet v1.1.408
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-09 18:48:57,458 - ControlNet - INFO - ControlNet v1.1.408
sd-webui-prompt-all-in-one background API service started successfully.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
dirname:  D:\AI\stable-diffusion-webui\localizations
localizations:  {'zh-Hans (Stable) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable) [vladmandic].json', 'zh-Hans (Stable)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing) [vladmandic].json', 'zh-Hans (Testing)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
Loading weights [31e35c80fc] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
D:\AI\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
Creating model from config: D:\AI\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.5s (prepare environment: 6.0s, import torch: 4.6s, import gradio: 0.8s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.8s, setup codeformer: 0.1s, load scripts: 7.4s, create ui: 1.2s, gradio launch: 0.7s, app_started_callback: 0.9s).
Applying attention optimization: xformers... done.
Model loaded in 13.2s (load weights from disk: 1.5s, create model: 1.4s, apply weights to model: 5.8s, calculate empty prompt: 4.3s).

**Comment by portu-sim** [comment]
from sd_bmab import dinosam, process, detailing, parameters, util, controlnet, constants <-- this codes are old components. now they are removed.
after new version of BMAB is installed. It works.
