### ISSUE TITLE
BMAB API 사용시 오류.

### ISSUE THREAD

**Issue by suhun96** [portu-sim/sd-webui-bmab#20]
"alwayson_scripts"에서 "BMAB"으로 작성했을 때 API가 정상적으로 작동하지 않습니다. API payload를 확인해본 결과, "BMAB Extension"을 사용해야 API가 올바르게 작동하는 것으로 보입니다. 이에 따라 API 문서도 수정이 필요할 것으로 판단됩니다. 확인 부탁드립니다.

**Comment by suhun96** [comment]
"BMAB Extension" 으로 다시 시도해본 결과 똑같이 적용이 되지않고 있는것 같습니다. 
api docs에 작성해주신 예제 그대로 작동시키면 오류가 나오고 있습니다. 오류 내용은 다음과 같습니다.

{'error': 'HTTPException', 'detail': "Script 'BMAB' not found", 'body': '', 'errors': ''}

<img width="657" alt="스크린샷 2024-01-03 오후 7 48 51" src="https://github.com/portu-sim/sd-webui-bmab/assets/97911154/55995f62-0202-46f6-bd91-2fe036757777">

**Comment by portu-sim** [comment]
최신 코드에서 BMAB로 변경이 되었습니다. 사용하시는 버전이 얼마인지 확인 부탁드립니다.

**Comment by suhun96** [comment]
버전 문제가 맞았습니다. 친절한 답변 감사합니다~!!
