### ISSUE TITLE
Can't find "Process before Img2Img"

### ISSUE THREAD

**Issue by wardensc2** [portu-sim/sd-webui-bmab#21]
Hi Portu-sim

I try to merge 2 image into one by using imaging tab in BMAB but in the latest version I dont find "Process before Img2Img" to check.

Do I need to enable something to make it appear ?

**Comment by portu-sim** [comment]
You should install Grounding DINO.
You can install the package in 'BMAB Config, Preset, Installer'

**Comment by wardensc2** [comment]
I think I already install Grounding DINO but still can't find Process before Img2Img:
![image](https://github.com/portu-sim/sd-webui-bmab/assets/77379748/f774b3d8-d8ed-45e3-bedc-2ceefa625194)

And when I try to run imaging BMAB doesn't work. SD still running like img2img

**Comment by portu-sim** [comment]
Oh..I see...'process before img2img' is removed option.
please check this document.
https://github.com/portu-sim/sd-webui-bmab/blob/main/docs/masking.md

**Comment by wardensc2** [comment]
> Oh..I see...'process before img2img' is removed option. please check this document. https://github.com/portu-sim/sd-webui-bmab/blob/main/docs/masking.md

I try to follow your document but the check "process before img2img" is still disappeared. And the BMAB imaging option doesn't work at all, I try to turn on and off and the result is still the same

**Comment by portu-sim** [comment]
Sorry,  https://github.com/portu-sim/sd-webui-bmab/blob/main/docs/masking.md this document is old one as well.

This is right setting.

<img width="1103" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/6b8eaa17-0eda-4ee1-9dd4-acfc9947db8d">

**Comment by wardensc2** [comment]
> Sorry, https://github.com/portu-sim/sd-webui-bmab/blob/main/docs/masking.md this document is old one as well.
> 
> This is right setting.
> 
> <img alt="image" width="1103" src="https://private-user-images.githubusercontent.com/141602933/297106708-6b8eaa17-0eda-4ee1-9dd4-acfc9947db8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjQ0NDgsIm5iZiI6MTcwNTY2NDE0OCwicGF0aCI6Ii8xNDE2MDI5MzMvMjk3MTA2NzA4LTZiOGVhYTE3LTBlZGEtNGVlMS05ZGQ0LWFjZmM5OTQ3ZGI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxMTM1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGFiNDUzYTI3MTY2MjhlNTk0NzZjMzA5ODc5N2U4MzAzZWY5NGU1NWYyMGRhMjg0MDc2M2VhYmUwZDczMDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nKl__CzHbVXYj3KADo4oy1meRLCekI9oxdhpBTo7dLQ">
> Please set denoising strength to be 0.4

I try to do as you said but BMAB does not run at all, other functions still work well, can you run a test by yourself and show me  the image

**Comment by wardensc2** [comment]
It seem like BMAB wont download GroundDINO model although it said I already installed. Can you fixed it or show me where to download the model and what folder I need to put it in BMAB please. Thank you

![image](https://github.com/portu-sim/sd-webui-bmab/assets/77379748/c499f6f6-2dc9-49d6-a338-fc7bf9421e80)
