### ISSUE TITLE
How to install Grounddino Manually

### ISSUE THREAD

**Issue by wardensc2** [portu-sim/sd-webui-bmab#23]
Hi portu-sim

Please tell me how to install GroudDINO model manually the installer keep saying GroundDINO installed but when I running any BMAB task using GroundDINO I always get this:

![image](https://github.com/portu-sim/sd-webui-bmab/assets/77379748/0c4d2307-7bf9-4690-9a2c-08eece263531)

I downloaded GroundDINO model already but don't know where to put it in.

**Comment by portu-sim** [comment]
You can install GroudingDINO in BMAB TAB
<img width="933" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/f0e064eb-e442-4598-8cbb-b1d79086a756">
