### ISSUE TITLE
Please add a version for Stable Diffusion Forge

### ISSUE THREAD

**Issue by wardensc2** [portu-sim/sd-webui-bmab#28]
Hi Portu-Sim

Please update your BMAB extension to support stable diffusion Forge. 

https://github.com/lllyasviel/stable-diffusion-webui-forge

Now when install BMAB in Forge, it disable Controlnet Intergrate of Forge. Uninstall BMAB problem gone

Thank you so much

**Comment by portu-sim** [comment]
Sorry. I have no time to support forked stable diffusion webui.
