### ISSUE TITLE
Hi, after i update to SD1.8, i have this issue that sd-webui-bmab cannot be load, may i know any solution to fix this? Thank you

### ISSUE THREAD

**Issue by DK22024** [portu-sim/sd-webui-bmab#29]
![sd-webui-bmab Issue](https://github.com/portu-sim/sd-webui-bmab/assets/162413242/93ac5deb-bb01-423c-953f-d1571ceaf03c)

**Comment by ArmyOfPun1776** [comment]
> ![sd-webui-bmab Issue](https://private-user-images.githubusercontent.com/162413242/310382305-93ac5deb-bb01-423c-953f-d1571ceaf03c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODgwNTEsIm5iZiI6MTcwOTk4Nzc1MSwicGF0aCI6Ii8xNjI0MTMyNDIvMzEwMzgyMzA1LTkzYWM1ZGViLWJiMDEtNDIzYy05NTNmLWQxNTcxY2VhZjAzYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxMjM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQxYWJiYzZmNGFlMjM5MzFlMWRmODgxMTI1MGU2ZDU4MjAwZjhlYWJjMjI3N2U5MzFhODkzNzUxM2Y1Y2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dLehxfu9JeOInI_EYfZYEx_CD5EKtq_QOSi1upFXI2g)

Hi There!

So I was having the same issue.  I'm on 1.8 as well though I don't think the error has anything to do with the 1.8 update. If I'm wrong I'm wrong. I didn't install this Extension until after I was already on v1.8. 

It seems that, maybe, at some point the `.py` file the extension is looking for `basicsr.py` was removed from the archive.  This can be traced by opening the `bmab.py` file in the extensions directory and following the `imports`

-or-

Simply looking at the last line of the error thrown by Automatic1111: `File "C:\SD1.8\weui\extensions\sd-webui-bmab\util.py", line 8, in <module> ModuleNotFoundError: No module named 'basicsr'`

Line 8 in `util.py` is `from basicsr.utils.download_util import load_file_from_url`

This is the line creating the conflict.  The script seems to be looking for a file called `basicsr` and some lines of code within it called `download_util` under a `util` parameter.  This code previously pointed to a `url` that was downloading some files for the extension, I guess. 

In an earlier version the creator may have had this `call` present to save on space or something.  I'm not really sure.  But since the file doesn't exist in the `.git` I assume it's an obsolete line of code and is unnecessary for the extension to function as intended. 

So... What did I do to make it work?  I removed line 8 in the `util.py` file `from basicsr.utils.download_util import load_file_from_url`.  

Behold!  The extension works as expected so far. Though I'm only really using the extension to do some minor Image enhancements.  I haven't gotten into the more "advanced" settings and utilities yet. 

Hope this helps.  And I'm sure if I'm wrong about any of this; The creator will lay into me.  lol

**Comment by portu-sim** [comment]
Thank you. update soon.

**Comment by nitinmukesh** [comment]
To fix this issue.
1. Open command prompt and navigate to path where webui is installed e.g.

<img width="393" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/2102186/26debbb1-0dcf-4dcd-9d9b-44aaaf6570ac">


2. venv\scripts\activate.bat
3. pip install basicsr

Close command prompt and launch WebUI.

**Comment by rungvang** [comment]
> To fix this issue.
> 
>     1. Open command prompt and navigate to path where webui is installed e.g.
> 
> 
> <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/2102186/315519227-26debbb1-0dcf-4dcd-9d9b-44aaaf6570ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNTQ4MDEsIm5iZiI6MTcxMTA1NDUwMSwicGF0aCI6Ii8yMTAyMTg2LzMxNTUxOTIyNy0yNmRlYmJiMS0wZGNmLTRkY2QtOWQ5Yi00NGFhYWY2NTcwYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMjA1NTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE1MDlhODJmODIxNmNmZTI1MDNhM2NhNThkOTYxMjg3Mzc3NDc3YzY0Yjg2MDM5NWQzOTZiY2E1MTAyMzU0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3MAh-eKWdOiwx3M2gSiphmpbV_aLZ1FLzt12aUttgP0">
> 
>     2. venv\scripts\activate.bat
> 
>     3. pip install basicsr
> 
> 
> Close command prompt and launch WebUI.

Does not work for me 


![345356](https://github.com/portu-sim/sd-webui-bmab/assets/126343000/a0b5292b-7437-454c-b475-64fdd0c6be0d)

**Comment by rungvang** [comment]
> > To fix this issue.
> > 
> > 1. Open command prompt and navigate to path where webui is installed e.g.
> > 
> > <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/2102186/315519227-26debbb1-0dcf-4dcd-9d9b-44aaaf6570ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDc1MzIsIm5iZiI6MTcxMTA0NzIzMiwicGF0aCI6Ii8yMTAyMTg2LzMxNTUxOTIyNy0yNmRlYmJiMS0wZGNmLTRkY2QtOWQ5Yi00NGFhYWY2NTcwYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTg1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjMWZiZmE2OGQ0ZjU1ODFjNDcwMmNmNmZhNzczMzI5ZWE0MDU2NWJlZDFjMTFmNDdkNmRjMjA3ZDhjOWM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QMrX2w4fyxjsM5cnullpmsACLiNtMJsIvUluVsEtHro">
> > 2. venv\scripts\activate.bat
> > 3. pip install basicsr
> > Close command prompt and launch WebUI.
> 
> Thanks... but how do you navigate to a .bat file exactly? I've never seen or done that before. I mean I'm all good getting to the scripts folder... but... wha?

Navigate to your SD folder, type "cmd" on the upper adress bar -> it will open cmd with the path to your SD folder with something like this: C:\stable_diffusion>, then you type next command directly in the cmd: venv\scripts\activate.bat, Hit Enter. Type: pip install basicsr. Hit Enter.

**Comment by ArmyOfPun1776** [comment]
> > > To fix this issue.
> > > 
> > > 1. Open command prompt and navigate to path where webui is installed e.g.
> > > 
> > > <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/2102186/315519227-26debbb1-0dcf-4dcd-9d9b-44aaaf6570ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDc1MzIsIm5iZiI6MTcxMTA0NzIzMiwicGF0aCI6Ii8yMTAyMTg2LzMxNTUxOTIyNy0yNmRlYmJiMS0wZGNmLTRkY2QtOWQ5Yi00NGFhYWY2NTcwYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTg1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjMWZiZmE2OGQ0ZjU1ODFjNDcwMmNmNmZhNzczMzI5ZWE0MDU2NWJlZDFjMTFmNDdkNmRjMjA3ZDhjOWM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QMrX2w4fyxjsM5cnullpmsACLiNtMJsIvUluVsEtHro">
> > > 2. venv\scripts\activate.bat
> > > 3. pip install basicsr
> > > Close command prompt and launch WebUI.
> > 
> > 
> > Thanks... but how do you navigate to a .bat file exactly? I've never seen or done that before. I mean I'm all good getting to the scripts folder... but... wha?
> 
> Navigate to your SD folder, type "cmd" on the upper adress bar -> it will open cmd with the path to your SD folder, you will see something like this: C:\stable_diffusion>, then you type next command directly in the cmd:
> 
> venv\scripts\activate.bat
> 
> Hit Enter then type:
> 
> pip install basicsr
> 
> Hit Enter.
> 
> ![345356](https://private-user-images.githubusercontent.com/126343000/315691924-8d90971f-6e26-42a4-9e21-d67cb81521a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjA4MDIsIm5iZiI6MTcxMTA2MDUwMiwicGF0aCI6Ii8xMjYzNDMwMDAvMzE1NjkxOTI0LThkOTA5NzFmLTZlMjYtNDJhNC05ZTIxLWQ2N2NiODE1MjFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQyMjM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2MwMWFlNWJmY2U3Mzk1NmMzNDA3ZTQ0YWI1NjI0YTQzOWJhYzVkYjEyN2M1ZTUzYzY5ZjZiNGM3YTg2MGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOs8yzQ9j_tu-iodKGZu4sUFgj-W1ggEimcc9_lfTnE)

OK.  I'm with you.  Ran the commands. got a dialog. installed a bunch of files. started the UI. Same error for bmab. 

Closed WebUI. returned to cmd. navigated to target again. ran command. All requirements satisfied.  So it is installed. hrm. 

Thanks for the info though. I'll be messing around with it more here in a little bit.

**Comment by rungvang** [comment]
> > > > To fix this issue.
> > > > 
> > > > 1. Open command prompt and navigate to path where webui is installed e.g.
> > > > 
> > > > <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/2102186/315519227-26debbb1-0dcf-4dcd-9d9b-44aaaf6570ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDc1MzIsIm5iZiI6MTcxMTA0NzIzMiwicGF0aCI6Ii8yMTAyMTg2LzMxNTUxOTIyNy0yNmRlYmJiMS0wZGNmLTRkY2QtOWQ5Yi00NGFhYWY2NTcwYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTg1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjMWZiZmE2OGQ0ZjU1ODFjNDcwMmNmNmZhNzczMzI5ZWE0MDU2NWJlZDFjMTFmNDdkNmRjMjA3ZDhjOWM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QMrX2w4fyxjsM5cnullpmsACLiNtMJsIvUluVsEtHro">
> > > > 2. venv\scripts\activate.bat
> > > > 3. pip install basicsr
> > > > Close command prompt and launch WebUI.
> > > 
> > > 
> > > Thanks... but how do you navigate to a .bat file exactly? I've never seen or done that before. I mean I'm all good getting to the scripts folder... but... wha?
> > 
> > 
> > Navigate to your SD folder, type "cmd" on the upper adress bar -> it will open cmd with the path to your SD folder, you will see something like this: C:\stable_diffusion>, then you type next command directly in the cmd:
> > venv\scripts\activate.bat
> > Hit Enter then type:
> > pip install basicsr
> > Hit Enter.
> > ![345356](https://private-user-images.githubusercontent.com/126343000/315691924-8d90971f-6e26-42a4-9e21-d67cb81521a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjA4MDIsIm5iZiI6MTcxMTA2MDUwMiwicGF0aCI6Ii8xMjYzNDMwMDAvMzE1NjkxOTI0LThkOTA5NzFmLTZlMjYtNDJhNC05ZTIxLWQ2N2NiODE1MjFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQyMjM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2MwMWFlNWJmY2U3Mzk1NmMzNDA3ZTQ0YWI1NjI0YTQzOWJhYzVkYjEyN2M1ZTUzYzY5ZjZiNGM3YTg2MGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOs8yzQ9j_tu-iodKGZu4sUFgj-W1ggEimcc9_lfTnE)
> 
> OK. I'm with you. Ran the commands. got a dialog. installed a bunch of files. started the UI. Same error for bmab.
> 
> Closed WebUI. returned to cmd. navigated to target again. ran command. All requirements satisfied. So it is installed. hrm.
> 
> Thanks for the info though. I'll be messing around with it more here in a little bit.


Strange, I have the same error not only for bmab but also for openpose. After installed the basicsr the problem is fixed. My python ver is 3.10.10. Pip ver 24.0.

**Comment by ArmyOfPun1776** [comment]
> > > > > To fix this issue.
> > > > > 
> > > > > 1. Open command prompt and navigate to path where webui is installed e.g.
> > > > > 
> > > > > <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/2102186/315519227-26debbb1-0dcf-4dcd-9d9b-44aaaf6570ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDc1MzIsIm5iZiI6MTcxMTA0NzIzMiwicGF0aCI6Ii8yMTAyMTg2LzMxNTUxOTIyNy0yNmRlYmJiMS0wZGNmLTRkY2QtOWQ5Yi00NGFhYWY2NTcwYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTg1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjMWZiZmE2OGQ0ZjU1ODFjNDcwMmNmNmZhNzczMzI5ZWE0MDU2NWJlZDFjMTFmNDdkNmRjMjA3ZDhjOWM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QMrX2w4fyxjsM5cnullpmsACLiNtMJsIvUluVsEtHro">
> > > > > 2. venv\scripts\activate.bat
> > > > > 3. pip install basicsr
> > > > > Close command prompt and launch WebUI.
> > > > 
> > > > 
> > > > Thanks... but how do you navigate to a .bat file exactly? I've never seen or done that before. I mean I'm all good getting to the scripts folder... but... wha?
> > > 
> > > 
> > > Navigate to your SD folder, type "cmd" on the upper adress bar -> it will open cmd with the path to your SD folder, you will see something like this: C:\stable_diffusion>, then you type next command directly in the cmd:
> > > venv\scripts\activate.bat
> > > Hit Enter then type:
> > > pip install basicsr
> > > Hit Enter.
> > > ![345356](https://private-user-images.githubusercontent.com/126343000/315691924-8d90971f-6e26-42a4-9e21-d67cb81521a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjA4MDIsIm5iZiI6MTcxMTA2MDUwMiwicGF0aCI6Ii8xMjYzNDMwMDAvMzE1NjkxOTI0LThkOTA5NzFmLTZlMjYtNDJhNC05ZTIxLWQ2N2NiODE1MjFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQyMjM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2MwMWFlNWJmY2U3Mzk1NmMzNDA3ZTQ0YWI1NjI0YTQzOWJhYzVkYjEyN2M1ZTUzYzY5ZjZiNGM3YTg2MGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOs8yzQ9j_tu-iodKGZu4sUFgj-W1ggEimcc9_lfTnE)
> > 
> > 
> > OK. I'm with you. Ran the commands. got a dialog. installed a bunch of files. started the UI. Same error for bmab.
> > Closed WebUI. returned to cmd. navigated to target again. ran command. All requirements satisfied. So it is installed. hrm.
> > Thanks for the info though. I'll be messing around with it more here in a little bit.
> 
> Strange, I have the same error not only for bmab but also for openpose. After installed the basicsr the problem is fixed. My python ver is 3.10.10. Pip ver 24.0.

Yep, same ver of Python and Pip for me as well.  Not sure why it would behave like that... Might have to do a clean install to test... Or a branch... Yeah It hink I'll do a Branch... My poor SSD. lol

**Comment by portu-sim** [comment]
Code Fixed
