### ISSUE TITLE
Stable Diffusion web ui API 이용한 호출 가능한가요?

### ISSUE THREAD

**Issue by bodybreaker** [portu-sim/sd-webui-bmab#3]
Stable Diffusion web ui API 이용한 호출 가능한가요?

**Comment by portu-sim** [comment]
현재는 지원하지 않습니다. 추후 지원할 수 있도록 하겠습니다.

**Comment by portu-sim** [comment]
기능 업데이트 되었습니다. API를 이용해서 BMAB를 사용할 수 있습니다. 문서가 업데이트 되었습니다.
