### ISSUE TITLE
SDNEXT backcompatibility ^^ Sorryyy

### ISSUE THREAD

**Issue by RGX650** [portu-sim/sd-webui-bmab#36]
Any advice 
about how i could maintain more seamlessly my SDNEXT fork 
with cleaner pull requests  ?

Sorry you are the unlucky one, 
i learned github with your BMAB project !

**Comment by portu-sim** [comment]
I have no time to manage code for SDNEXT. 
Please keep your SDNEXT code in your repository.
Many guys get code from your repository.

**Comment by RGX650** [comment]
ok thanks.
I added yolov models download at install. worked fine.

maybe you could take it
https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/install.py
