### ISSUE TITLE
생성중에 huggingface에 접속하는 이슈

### ISSUE THREAD

**Issue by jake1402k** [portu-sim/sd-webui-bmab#4]
프록시가 있는 환경에서 실행을 하고 있습니다
로컬에서 가능한 파일을 다운로드하여 테스트 및 실행 합니다만 
bmab 사용중 매 실행시 huggingface 로딩을 하여 try에러가 발생합니다. 

혹시 오프라인이나 프록시 있는 환경에서도 테스트 할 수 있는 방법이 있을까요? 

`
---
100%|██████████████████████████████████████████████████████████████████████████████████| 39/39 [00:03<00:00, 11.60it/s]
Loading config {100%|██████████████████████████████████████████████████████████████████| 39/39 [00:03<00:00, 11.91it/s]
  "enabled": true,
  "contrast": 1.2,
  "brightness": 0.9,
  "sharpeness": 1.5,
  "edge_flavor_enabled": true,
  "edge_low_threadhold": 50,
  "edge_high_threadhold": 200,
  "edge_strength": 0.5,
  "resize_by_person_enabled": true,
  "resize_by_person": 0.85,
  "face_detailing_enabled": true,
  "module_config": {
    "face_detailing": {
      "denoising_strength": 0.4,
      "prompt": "smile, #!org!#",
      "inpaint_full_res": true,
      "inpaint_full_res_padding": 32,
      "cfg_scale": 7
    },
    "face_detailing_opt": {
      "mask dilation": 4
    }
  }
}
final text_encoder_type: bert-base-uncased

'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016CE6E2D3F0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: a1af9c4d-9d84-4250-b317-caedc5a8eb50)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json
Total progress: 100%|██████████████████████████████████████████████████████████████████| 39/39 [03:21<00:00, 11.91it/s]WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016CE6E2D3F0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: a1af9c4d-9d84-4250-b317-caedc5a8eb50)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncase'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016CE71215D0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 0ff6c544-0045-45bd-8bcd-5589459f274c)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016CE71215D0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 0ff6c544-0045-45bd-8bcd-5589459f274c)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json
`

**Comment by aierbaipang** [comment]
the same problem,how can the author solve it

**Comment by portu-sim** [comment]
필요한 모델을 해당 시점에 로드하기 때문에 발생하는 문제로 보입니다.
사전에 미리 전체가 로드되어야 하는 환경인가요?

**Comment by portu-sim** [comment]
https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth
https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swint_ogc.pth
https://raw.githubusercontent.com/IDEA-Research/GroundingDINO/main/groundingdino/config/GroundingDINO_SwinT_OGC.py
https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n_v2.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8s.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8m-seg.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt
https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt
https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_b.pth
https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_h.pth
https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_l.pth
https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_tiny.pth

이 파일들을 다운로드 하셔서 stable-diffusion-webui/models/bmab 에 넣으시면 더 이상 다운받지 않습니다.
