### ISSUE TITLE
오늘 업데이트했는데요.

### ISSUE THREAD

**Issue by taimati** [portu-sim/sd-webui-bmab#8]
안녕하세요.
오늘 업데이트했는데
BMAB  컨트롤넷에서 Enable ControlNet access
사용해여 노이즈를 추가할려고했는데 안되네요.

오류는
TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'resize mode'
이렇게 나옵니다.

그리고
BMAB Preprocessor
크기조정
Enable resize (intermediate)
이걸 해도
오류가
TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'resize mode'
동일하게 나옵니다.

리사이즈 모드가 무슨 문제가 있는거같아요.

**Comment by portu-sim** [comment]
오류난 부분 전체를 긁어서 붙여주시면 도움이 됩니다.

**Comment by portu-sim** [comment]
ControlNet 1.1.416 최근 코드에서 오류 내는 것을 확인했습니다.
수정 버전 올려드리겠습니다.

**Comment by taimati** [comment]
감사합니다. 잘쓰고있어요!!
